const { THEME } = require('./pdfTheme');

function renderFooter(doc) {
    doc.moveDown(1);
    doc.moveTo(THEME.margins.left, doc.y)
        .lineTo(THEME.margins.left + THEME.contentWidth, doc.y)
        .stroke(THEME.colors.lightGray);
    doc.moveDown(0.3);
    doc.fontSize(8).font(THEME.fonts.regular).fillColor(THEME.colors.lightText);
    doc.text(
        'This report is generated by the KSP Crime Intelligence Platform. For official use only.',
        { align: 'center' }
    );
    doc.fillColor('#000000');
}

module.exports = { renderFooter };
