export const mockCriminalNetworkData = {
  nodes: [
    { id: 'central_1', label: 'Ravi Kumar', type: 'central', total_cases: 12, risk_score: 0.95, role: 'LEADER', community_id: 0 },
    { id: 'accused_1', label: 'Suresh Reddy', type: 'accused', total_cases: 8, risk_score: 0.82, role: 'BROKER', community_id: 0 },
    { id: 'accused_2', label: 'Mahesh Gowda', type: 'accused', total_cases: 6, risk_score: 0.71, role: 'HUB', community_id: 0 },
    { id: 'accused_3', label: 'Venkatesh Nair', type: 'accused', total_cases: 5, risk_score: 0.65, role: 'MEMBER', community_id: 0 },
    { id: 'accused_4', label: 'Prakash Shetty', type: 'accused', total_cases: 4, risk_score: 0.58, role: 'MEMBER', community_id: 1 },
    { id: 'accused_5', label: 'Anil Sharma', type: 'accused', total_cases: 7, risk_score: 0.78, role: 'BROKER', community_id: 1 },
    { id: 'accused_6', label: 'Deepak Rao', type: 'accused', total_cases: 3, risk_score: 0.45, role: 'HABITUAL', community_id: 1 },
    { id: 'accused_7', label: 'Kiran Bhat', type: 'accused', total_cases: 2, risk_score: 0.35, role: 'MEMBER', community_id: 2 },
    { id: 'accused_8', label: 'Rajesh Menon', type: 'accused', total_cases: 5, risk_score: 0.62, role: 'HUB', community_id: 2 },
    { id: 'victim_1', label: 'Lakshmi Devi', type: 'victim', total_cases: 1, risk_score: 0, role: null, community_id: null },
    { id: 'victim_2', label: 'Sarojini M.', type: 'victim', total_cases: 1, risk_score: 0, role: null, community_id: null },
    { id: 'victim_3', label: 'Harish Pai', type: 'victim', total_cases: 1, risk_score: 0, role: null, community_id: null },
    { id: 'fir_1', label: 'FIR-2026-0042', type: 'fir', total_cases: 1, risk_score: 0, role: null, community_id: null },
    { id: 'fir_2', label: 'FIR-2026-0087', type: 'fir', total_cases: 1, risk_score: 0, role: null, community_id: null },
    { id: 'fir_3', label: 'FIR-2025-0156', type: 'fir', total_cases: 1, risk_score: 0, role: null, community_id: null },
    { id: 'fir_4', label: 'FIR-2026-0103', type: 'fir', total_cases: 1, risk_score: 0, role: null, community_id: null },
    { id: 'loc_1', label: 'Bangalore Central', type: 'location', total_cases: 8, risk_score: 0, role: null, community_id: null },
    { id: 'loc_2', label: 'Mysore North', type: 'location', total_cases: 4, risk_score: 0, role: null, community_id: null },
    { id: 'loc_3', label: 'Hubli East', type: 'location', total_cases: 3, risk_score: 0, role: null, community_id: null },
    { id: 'mo_1', label: 'Armed Robbery', type: 'mo', total_cases: 5, risk_score: 0, role: null, community_id: null },
    { id: 'mo_2', label: 'Cyber Fraud', type: 'mo', total_cases: 3, risk_score: 0, role: null, community_id: null },
    { id: 'mo_3', label: 'Drug Trafficking', type: 'mo', total_cases: 4, risk_score: 0, role: null, community_id: null },
  ],
  edges: [
    { source: 'central_1', target: 'accused_1', label: 'CO_ACCUSED', weight: 3 },
    { source: 'central_1', target: 'accused_2', label: 'CO_ACCUSED', weight: 2 },
    { source: 'accused_1', target: 'accused_3', label: 'CO_ACCUSED', weight: 2 },
    { source: 'accused_2', target: 'accused_4', label: 'CO_ACCUSED', weight: 1 },
    { source: 'accused_5', target: 'accused_6', label: 'CO_ACCUSED', weight: 2 },
    { source: 'accused_5', target: 'accused_4', label: 'CO_ACCUSED', weight: 1 },
    { source: 'accused_7', target: 'accused_8', label: 'CO_ACCUSED', weight: 1 },
    { source: 'accused_8', target: 'accused_2', label: 'SHARED_LOCATION', weight: 1 },
    { source: 'central_1', target: 'fir_1', label: 'ACCUSED_OF', weight: 1 },
    { source: 'accused_1', target: 'fir_1', label: 'ACCUSED_OF', weight: 1 },
    { source: 'accused_2', target: 'fir_2', label: 'ACCUSED_OF', weight: 1 },
    { source: 'accused_5', target: 'fir_3', label: 'ACCUSED_OF', weight: 1 },
    { source: 'accused_7', target: 'fir_4', label: 'ACCUSED_OF', weight: 1 },
    { source: 'victim_1', target: 'fir_1', label: 'VICTIM_OF', weight: 1 },
    { source: 'victim_2', target: 'fir_3', label: 'VICTIM_OF', weight: 1 },
    { source: 'victim_3', target: 'fir_4', label: 'VICTIM_OF', weight: 1 },
    { source: 'accused_1', target: 'loc_1', label: 'LOCATED_AT', weight: 1 },
    { source: 'accused_2', target: 'loc_1', label: 'LOCATED_AT', weight: 1 },
    { source: 'accused_5', target: 'loc_2', label: 'LOCATED_AT', weight: 1 },
    { source: 'accused_7', target: 'loc_3', label: 'LOCATED_AT', weight: 1 },
    { source: 'accused_1', target: 'mo_1', label: 'USES_MO', weight: 1 },
    { source: 'accused_2', target: 'mo_2', label: 'USES_MO', weight: 1 },
    { source: 'accused_5', target: 'mo_3', label: 'USES_MO', weight: 1 },
    { source: 'central_1', target: 'mo_1', label: 'USES_MO', weight: 1 },
  ],
  metrics: {
    totalNodes: 22,
    totalEdges: 24,
    density: 0.105,
    totalComponents: 3,
    topActors: [
      { id: 'central_1', label: 'Ravi Kumar', role: 'LEADER', composite_score: 0.95, total_cases: 12, betweenness: 0.82, degree: 7 },
      { id: 'accused_1', label: 'Suresh Reddy', role: 'BROKER', composite_score: 0.82, total_cases: 8, betweenness: 0.65, degree: 5 },
      { id: 'accused_5', label: 'Anil Sharma', role: 'BROKER', composite_score: 0.78, total_cases: 7, betweenness: 0.55, degree: 4 },
      { id: 'accused_2', label: 'Mahesh Gowda', role: 'HUB', composite_score: 0.71, total_cases: 6, betweenness: 0.48, degree: 5 },
      { id: 'accused_8', label: 'Rajesh Menon', role: 'HUB', composite_score: 0.62, total_cases: 5, betweenness: 0.35, degree: 3 },
    ],
  },
  communities: {
    '0': {
      id: 0,
      size: 4,
      accused_count: 4,
      fir_count: 2,
      avg_risk_score: 0.78,
      dominant_crime: 'Armed Robbery',
      members: [
        { id: 'central_1', label: 'Ravi Kumar', type: 'central' },
        { id: 'accused_1', label: 'Suresh Reddy', type: 'accused' },
        { id: 'accused_2', label: 'Mahesh Gowda', type: 'accused' },
        { id: 'accused_3', label: 'Venkatesh Nair', type: 'accused' },
      ],
    },
    '1': {
      id: 1,
      size: 3,
      accused_count: 3,
      fir_count: 2,
      avg_risk_score: 0.60,
      dominant_crime: 'Drug Trafficking',
      members: [
        { id: 'accused_4', label: 'Prakash Shetty', type: 'accused' },
        { id: 'accused_5', label: 'Anil Sharma', type: 'accused' },
        { id: 'accused_6', label: 'Deepak Rao', type: 'accused' },
      ],
    },
    '2': {
      id: 2,
      size: 2,
      accused_count: 2,
      fir_count: 1,
      avg_risk_score: 0.49,
      dominant_crime: 'Cyber Fraud',
      members: [
        { id: 'accused_7', label: 'Kiran Bhat', type: 'accused' },
        { id: 'accused_8', label: 'Rajesh Menon', type: 'accused' },
      ],
    },
  },
}
